name: "Install Edgee's CLI"
description: "Install edgee from www.github.com/edgee-cloud/edgee"
author: "edgee-cloud"

runs:
  using: "composite"
  steps:
    - name: Install Edgee
      run: |
        curl https://install.edgee.cloud | sh
        mv edgee /usr/local/bin/
        echo "added edgee to path"
      shell: bash

    - name: Verify Edgee installation
      run: edgee --version
      shell: bash
